### ISSUE TITLE
Server crashes from Computercraft

### ISSUE THREAD

**Issue by ghost** [LotuxPunk/AutoAfkKicker#6]
https://gist.github.com/Modpack-Support/414b56bf8726ffd90c6dc81705489c13

**Comment by LotuxPunk** [comment]
No more crashes : https://minecraft.curseforge.com/projects/autoafkkicker/files/2669694

CC change his API, so I can't get now the packet. SquidDev gonna maybe do something to allow addon/mod to check if the mod is used or not in the future.

Thanks for report !
