### ISSUE TITLE
Add permission

### ISSUE THREAD

**Issue by bigenergy** [LotuxPunk/AutoAfkKicker#7]
Please add permission to kick exempt (kick bypass)

Example: autoafkcicker.bypass

**Comment by LotuxPunk** [comment]
Isn't already a thing?

**Comment by LotuxPunk** [comment]
autoafkkicker.afk.bypass

**Comment by bigenergy** [comment]
It doesn't work

**Comment by bigenergy** [comment]
> autoafkkicker.afk.bypass

It doesn't work

**Comment by LotuxPunk** [comment]
Which permission mod do you use ?

**Comment by bigenergy** [comment]
> Which permission mod do you use ?

LuckPerms for bukkit/spigot.

**Comment by LotuxPunk** [comment]
You know this is a Forge mod ?

**Comment by Jeryn99** [comment]
I assume you're running some form of Bungeecord? @bigenergy

**Comment by bigenergy** [comment]
Some Forge mods that have their permissions work calmly with my bukkit luckperms.

**Comment by LotuxPunk** [comment]
I'm using the Forge's PermissionAPI. i'm not sure how to "fix that", Ill investigate. thanks for the report.

**Comment by LotuxPunk** [comment]
Can you tell me which mod work well with LuckPerms ? (on your server)

**Comment by bigenergy** [comment]
> Can you tell me which mod work well with LuckPerms ? (on your server)

Most likely it Custom NPC
